//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Personal_Information
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="First_Name")]
        [StringLength(15,ErrorMessage ="First Name not be exceed")]
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        [Required]
        [Display(Name = "Last_Name")]
        [StringLength(15, ErrorMessage = "Last Name not be exceed")]
        public string Last_Name { get; set; }
        [Required]
        [Display(Name = "Mobile_Number")]
        [StringLength(15, ErrorMessage = "Mobile Number not be exceed")]
        public string Mobile_Number { get; set; }
        [Required]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage ="Please Enter Your Valid E-Mail")]
        public string Email_Address { get; set; }
        [Required]
        [Display(Name = "Gender")]
        [StringLength(15, ErrorMessage = "Gender  not be exceed")]
        public string Gender { get; set; }
        [Required]
        [Display(Name = "Permanent_Address")]
        [StringLength(40, ErrorMessage = "Permanent Address  not be exceed")]
        public string Permanent_Address { get; set; }
    }
}
